version: v1
services:
    accounts-mssql-db:
      container_name: "accounts-mssql-db"
      image: mcr.microsoft.com/mssql/server
      ports:
        - "7070:1433"
      environment:
        - MSSQL_SA_PASSWORD=Sample123!
        - MSSQL_PID=Sample
        - ACCEPT_EULA=Y
      networks:
        - grpc-db-net

    accounts-grpc-web:
      container_name: "accounts-mssql-db"
      build: 
          context: ../../../
          dockerfile: ./Services/Services.Accounts/Accounts.Grpc/Dockerfile
      ports:
        - "6060:80"
      environment:
        - MSSQL_SA_PASSWORD=Sample123!
        - MSSQL_PID=Sample
        - ACCEPT_EULA=Y
      networks:
        - grpc-db-net
      depends_on:
        - accounts-mssql-db

networks:
  grpc-db-net:
    driver: bridge